force-app/main/default/objects/Zoom_Meeting__c/Zoom_Meeting__c.object-meta.xml
<CustomObject>
    <description>It contains all the meeting data</description>
    <label>Zoom Meeting</label>
    <nameField>
        <label>Zoom Meeting Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Meeting__c/fields/Agenda__c.field-meta.xml
<CustomField>
    <fullName>Agenda__c</fullName>
    <description>It stores the complete meeting agenda</description>
    <inlineHelpText>It stores the complete meeting agenda</inlineHelpText>
    <label>Agenda</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Allow_Multiple_Devices__c.field-meta.xml
<CustomField>
    <fullName>Allow_Multiple_Devices__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It Allows attendees to join from multiple devices</description>
    <inlineHelpText>It Allows attendees to join from multiple devices</inlineHelpText>
    <label>Allow Multiple Devices</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Auto_Register__c.field-meta.xml
<CustomField>
    <fullName>Auto_Register__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It specifies that user don&apos;t need to register to join any meeting if it is checked</description>
    <inlineHelpText>It specifies that user don&apos;t need to register to join any meeting if it is checked</inlineHelpText>
    <label>Auto Register</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>It stores meeting duration</description>
    <inlineHelpText>It stores meeting duration</inlineHelpText>
    <label>Duration (In Minutes)</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Enforce_Login__c.field-meta.xml
<CustomField>
    <fullName>Enforce_Login__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Only signed-in users can join this meeting</description>
    <inlineHelpText>Only signed-in users can join this meeting</inlineHelpText>
    <label>Enforce Login</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/HD_Video__c.field-meta.xml
<CustomField>
    <fullName>HD_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It tells that make video resolution Defaults to HD video</description>
    <inlineHelpText>It tells that make video resolution Defaults to HD video</inlineHelpText>
    <label>HD Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Host_Video__c.field-meta.xml
<CustomField>
    <fullName>Host_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It tells start the video when the host joins the webinar</description>
    <inlineHelpText>It tells start the video when the host joins the webinar</inlineHelpText>
    <label>Host Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Join_before_Host__c.field-meta.xml
<CustomField>
    <fullName>Join_before_Host__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It stores whether the invitee can join the meeting before the host</description>
    <inlineHelpText>It stores whether the invitee can join the meeting before the host</inlineHelpText>
    <label>Join before Host</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Meeting_Recording_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Recording_URL__c</fullName>
    <inlineHelpText>This stores the meeting recorded play url</inlineHelpText>
    <label>Meeting Recording URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <description>It contains the created meeting URL</description>
    <inlineHelpText>It contains the created meeting URL</inlineHelpText>
    <label>Meeting URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Panelist_Video__c.field-meta.xml
<CustomField>
    <fullName>Panelist_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It tells that start the video when panelists join the webinar</description>
    <inlineHelpText>It tells that start the video when panelists join the webinar</inlineHelpText>
    <label>Panelist Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Share_Recording_URL__c.field-meta.xml
<CustomField>
    <fullName>Share_Recording_URL__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Share Recording URL in the Thank you Email Notification. This Feature needs Thank you Email Notification Enabled.</inlineHelpText>
    <label>Share Recording URL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Share_Survey_Link__c.field-meta.xml
<CustomField>
    <fullName>Share_Survey_Link__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Share Survey Link in the Thank you Email Notification. This Feature needs Thank you Email Notification Enabled.</inlineHelpText>
    <label>Share Survey Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>It contains the Start Date of the meeting</description>
    <inlineHelpText>It contains the Start Date of the meeting</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Start_Participant_Video_on_Meeting_Join__c.field-meta.xml
<CustomField>
    <fullName>Start_Participant_Video_on_Meeting_Join__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Start video when participants join meeting</description>
    <inlineHelpText>Start video when participants join meeting</inlineHelpText>
    <label>Start Participant Video on Meeting Join</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>It contains the Start Time of the Meeting</description>
    <inlineHelpText>It contains the Start Time of the Meeting</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Survey_Link_URL__c.field-meta.xml
<CustomField>
    <fullName>Survey_Link_URL__c</fullName>
    <inlineHelpText>This URL redirects to the survey page.</inlineHelpText>
    <label>Survey Link URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Thank_you_notification__c.field-meta.xml
<CustomField>
    <fullName>Thank_you_notification__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Attendee will receive thank you email by checking this checkbox</inlineHelpText>
    <label>Thank you notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>(GMT+14:00) Line Is. Time (Pacific/Kiritimati)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:45/+13:45) Chatham Standard / Daylight Time (Pacific/Chatham)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00/+13:00) New Zealand Standard / Daylight Time (Pacific/Auckland)</fullName>
            </value>
            <value>
                <fullName>(GMT+13:00) Phoenix Is. Time (Pacific/Enderbury)</fullName>
            </value>
            <value>
                <fullName>(GMT+13:00) Tonga Time (Pacific/Tongatapu)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Fiji Time (Pacific/Fiji)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Petropavlovsk-Kamchatski Time (Asia/Kamchatka)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:30/+11:00) Lord Howe Standard / Daylight Time (Australia/Lord_Howe)</fullName>
            </value>
            <value>
                <fullName>(GMT+11:00) Norfolk Time (Pacific/Norfolk)</fullName>
            </value>
            <value>
                <fullName>(GMT+11:00) Solomon Is. Time (Pacific/Guadalcanal)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:00/+11:00) Australian Eastern Standard / Daylight Time (New South Wales) (Australia/Sydney)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:30/+9:30) Australian Central Standard / Daylight Time (South Australia) (Australia/Adelaide)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:30) Australian Central Standard Time (Northern Territory) (Australia/Darwin)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Japan Standard Time (Asia/Tokyo)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Korea Standard Time (Asia/Seoul)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Philippines Time (Asia/Manila)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Malaysia Time (Asia/Kuala_Lumpur)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) China Standard Time (Asia/Shanghai)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Singapore Time (Asia/Singapore)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) China Standard Time (Asia/Taipei)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Australian Western Standard Time (Australia/Perth)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Hong Kong Time (Asia/Hong_Kong)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) West Indonesia Time (Asia/Jakarta)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Indochina Time (Asia/Bangkok)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Indochina Time (Asia/Ho_Chi_Minh)</fullName>
            </value>
            <value>
                <fullName>(GMT+06:30) Myanmar Time (Asia/Rangoon)</fullName>
            </value>
            <value>
                <fullName>(GMT+06:00) Bangladesh Time (Asia/Dhaka)</fullName>
            </value>
            <value>
                <fullName>(GMT+05:45) Nepal Time (Asia/Kathmandu)</fullName>
            </value>
            <value>
                <fullName>(GMT+05:30) India Standard Time (Asia/Kolkata)</fullName>
            </value>
            <value>
                <fullName>(GMT+05:30) India Standard Time (Asia/Colombo)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <description>It stores topic of the meeting</description>
    <inlineHelpText>It stores topic of the meeting</inlineHelpText>
    <label>Topic</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/recordTypes/Meeting.recordType-meta.xml
<RecordType>
    <fullName>Meeting</fullName>
    <active>true</active>
    <description>It creates a meeting in the Zoom and contains all the fields related to the meeting</description>
    <label>Meeting</label>
</RecordType>

force-app/main/default/objects/Zoom_Meeting__c/recordTypes/Webinar.recordType-meta.xml
<RecordType>
    <fullName>Webinar</fullName>
    <active>true</active>
    <description>It creates a webinar in the Zoom and contains all the information related to the webinar</description>
    <label>Webinar</label>
</RecordType>

force-app/main/default/classes/SFZoom_LightningEventHandler.cls
/*
    The MIT License
    Copyright © 2020 DataColada Pty Ltd

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
 */

/******************************************************************************************************************
    Class Name  : SFZoom_LightningEventHandler
    Description : This class is responsible for managing zoom event from the lightning component as well as quick action.
    Date        : 24 Dec 2018.
    Author       : DataColada Pty Ltd
*******************************************************************************************************************/
public with sharing class SFZoom_LightningEventHandler {
    /******************************************************************************************************************
        Method Name  : getZoomEventDetails
        Description  : It fetches complete meeting details from the salesforce database and return to lightning component.
        Date         : 3 Jan 2019.
        Parameter1   : sfZoomEventId - It contains salesforce meeting object record id.
        Author       : DataColada Pty Ltd
    *******************************************************************************************************************/
    @AuraEnabled
    public static Map<String, Object> getZoomEventDetails(String sfZoomEventId){
        Map<String, Object> returnMap;
        try{
            if(String.isNotBlank(sfZoomEventId)){
                List<String> listOfZoomMeetingFields = new List<String>{'Name', 'Agenda__c', 'Duration__c', 
                    'Enforce_Login__c', 'Join_before_Host__c', 'Auto_Register__c', 
                    'Start_Date__c', 'Start_Time__c', 'Time_Zone__c', 'Topic__c',
                    'Start_Participant_Video_on_Meeting_Join__c', 'Meeting_URL__c', 'RecordTypeId',
                    'HD_Video__c', 'Panelist_Video__c', 'Allow_Multiple_Devices__c',
                    'Host_Video__c','Thank_you_notification__c','Share_Survey_Link__c',
                    'Share_Recording_URL__c','Survey_Link_URL__c','Meeting_Recording_URL__c'};
                if(SFZoom_AccessUtil.hasReadAccess(String.escapeSingleQuotes(sfZoomEventId)) 
                   && SFZoom_AccessUtil.objectIsAccessible('Zoom_Meeting__c') 
                   && SFZoom_AccessUtil.objectIsQueryable('Zoom_Meeting__c') 
                   && SFZoom_AccessUtil.fieldsAreAccessible('Zoom_Meeting__c', listOfZoomMeetingFields))
                {
                    List<Zoom_Meeting__c> listOfMeetingToEdit = [SELECT Name, Agenda__c, Duration__c, 
                                                                         Enforce_Login__c,Join_before_Host__c,
                                                                         Start_Date__c, Start_Time__c, Time_Zone__c, 
                                                                         Topic__c,Start_Participant_Video_on_Meeting_Join__c, 
                                                                         Meeting_URL__c, Auto_Register__c, RecordType.Name,
                                                                         Thank_you_notification__c,Share_Survey_Link__c,
                                                                         Share_Recording_URL__c,Survey_Link_URL__c,
                                                                         Meeting_Recording_URL__c
                                                                         FROM Zoom_Meeting__c WHERE ID = :String.escapeSingleQuotes(sfZoomEventId)];
                    String parentId = SFZoom_MeetingManagerUtility.FindParentObjectRecordIdFromZoomMeeting((Id)sfZoomEventId);
                    returnMap = SFZoom_MeetingHandlerExtension.FindInvitationDetails((Id)parentId, (Id)sfZoomEventId);
                    returnMap.put('event', listOfMeetingToEdit);
                    returnMap.put('parentId', parentId);
                }
            }
        }Catch(Exception ex){
            System.debug('SFZoom_LightningEventHandler - getZoomEventDetails - Exception: ' + ex.getMessage());
        }
        return returnMap;
    }

    /******************************************************************************************************************
        Method Name  : getRecordTypeDetails
        Description  : It fetches meeting record type id and name and bind it with a map.
        Date         : 3 Jan 2019.
        Author       : DataColada Pty Ltd
    *******************************************************************************************************************/
    @AuraEnabled
    public static Map<String, String> getRecordTypeDetails(){
        Map<String, String> mapOfZoomEventRecordTypeIdWithName = new Map<String, String>();
        try{
            if(SFZoom_AccessUtil.objectIsAccessible('RecordType') && SFZoom_AccessUtil.objectIsQueryable('RecordType') 
               && SFZoom_AccessUtil.fieldsAreAccessible('RecordType', new List<String>{'DeveloperName', 'SObjectType'}))
            {
                List<RecordType> listOfZoomRecordType = [SELECT DeveloperName FROM RecordType WHERE SObjectType = 'Zoom_Meeting__c'];            
                for(RecordType eventRecordType : listOfZoomRecordType){
                    mapOfZoomEventRecordTypeIdWithName.put(eventRecordType.Id, eventRecordType.DeveloperName);
                }
            }
        }Catch(Exception ex){
            System.debug('SFZoom_LightningEventHandler - getRecordTypeDetails - Exception: ' + ex.getMessage());
        }
        return mapOfZoomEventRecordTypeIdWithName;                         
    }

    /******************************************************************************************************************
        Method Name  : upsertZoomEvent
        Description  : It processes meeting/webinar record to upsert in database.
        Date         : 3 Jan 2019.
        Parameter1   : jsonObj - It contains meeting details in json format
        Parameter2   : parentId - It contains parent id of the meeting record
        Parameter3   : eventType - It contains event type whether the record is a meeting or webinar
        Author       : DataColada Pty Ltd
    *******************************************************************************************************************/
    @AuraEnabled
    public static Map<String, Object> upsertZoomEvent(String jsonObj, String parentId, String eventType){
        Map<String, Object> returnResult = new Map<String, Object>();
        try{
            Zoom_Meeting__c zoomMeeting = (Zoom_Meeting__c) JSON.deserialize(jsonObj, Zoom_Meeting__c.class);
            SFZoom_MeetingHandlerExtension SFZoomMeetingHandlerInstance; 
            
            if(zoomMeeting.Id == null){
                if(String.isNotBlank(parentId)){
                    SFZoomMeetingHandlerInstance = new SFZoom_MeetingHandlerExtension(null, (Id) parentId, false);
                    SFZoomMeetingHandlerInstance.meetingStartTime = zoomMeeting.Start_Time__c;
                    SFZoomMeetingHandlerInstance.zoomMeeting = zoomMeeting;
                    Boolean isWebinar;
                    eventType = String.isBlank(eventType) ? '' : eventType.toLowerCase();
                    if(eventType.equalsIgnoreCase(Label.Webinar_Record_Type_Name)){
                        isWebinar = true; 
                        SFZoomMeetingHandlerInstance.eventType = Label.Webinar_Record_Type_Name;
                    }
                    else if(eventType.equalsIgnoreCase(Label.Meeting_Record_Type_Name)){
                        isWebinar = false;
                        SFZoomMeetingHandlerInstance.eventType = Label.Meeting_Record_Type_Name;
                    }
                    if(SFZoomMeetingHandlerInstance.eventType != null){
                        String returnMessage = SFZoomMeetingHandlerInstance.CreateMeetingLightning(isWebinar);
                        
                        if(returnMessage instanceof Id){
                            returnResult.put('sfid', returnMessage);
                            returnResult.put('attendees', SFZoom_MeetingHandlerExtension.FindListOfContactOrLeadFromChildRecords((Id)parentId));
                        }else
                            returnResult.put('error', returnMessage);            
                    }
                    else
                        returnResult.put('error', Label.Wrong_event_type);
                }
                else{
                    returnResult.put('error', Label.Invalid_Set_up_Object_Detail); 
                }                     
            }
            else{
                SFZoomMeetingHandlerInstance = new SFZoom_MeetingHandlerExtension(zoomMeeting.Id, (Id)parentId, false);                
                SFZoomMeetingHandlerInstance.zoomMeeting = zoomMeeting;
                SFZoomMeetingHandlerInstance.eventType = eventType;
                Datetime toupdate=  DateTime.newInstanceGMT(zoomMeeting.Start_Date__c, zoomMeeting.Start_Time__c);
                SFZoomMeetingHandlerInstance.meetingStartTime = Time.newInstance(toupdate.hourGMT(),toupdate.minuteGMT(),toupdate.secondGMT(),0);
                String returnMessage = SFZoomMeetingHandlerInstance.UpdateMeetingDetailsLightning();
                if(returnMessage instanceof Id)
                    returnResult.put('success', Label.Event_updated_successfully);
                else
                    returnResult.put('error', returnMessage);
            }            
        }Catch(Exception ex){
            System.debug('SFZoom_LightningEventHandler - upsertZoomEvent - Exception: ' + ex.getMessage());
        }        
        return returnResult;
    }
    
    /******************************************************************************************************************
        Method Name  : getRecordTypeDetails
        Description  : It fetches default meeting/webinar settings.
        Date         : 3 Jan 2019.
        Author       : DataColada Pty Ltd
    *******************************************************************************************************************/
    @AuraEnabled
    public static Zoom_Meeting__c loadExistingConfiguration(){
        try{
            SFZoom_MeetingHandlerExtension SFZoomMeetingHandlerInstance = new SFZoom_MeetingHandlerExtension();
            SFZoomMeetingHandlerInstance.zoomMeeting = new Zoom_Meeting__c();
            return SFZoomMeetingHandlerInstance.LoadExistingConfiguration();  
        }catch(Exception ex){
            System.debug('SFZoom_LightningEventHandler - loadExistingConfiguration - Exception: ' + ex.getMessage());
            return null;
        }
    }
    
   /******************************************************************************************************************
        Method Name  : getRecordTypeDetails
        Description  : It sends invite email to selected attendees.
        Date         : 3 Jan 2019.
        Parameter1   : sfMeetingId - It contains salesforce meeting record id
        Parameter2   : isUpdate - It tells whether it is a update or insert operation
        Parameter3   : jsonAttendees - It contains details of all the selected member in the json format
        Author       : DataColada Pty Ltd
    *******************************************************************************************************************/
    @AuraEnabled
    public static Map<Boolean, String> sendInviteEmail(String sfMeetingId,string parent, Boolean isUpdate, String jsonAttendees){
        Map<Boolean, String> returnResult = new Map<Boolean, String>();
        try{
            if(String.isBlank(sfMeetingId))
                returnResult.put(false, Label.Missing_meeting_detail);
            else{
                List<SFZoom_MeetingHandlerExtension.InviteeDetailsWrapper> lstAttendees = (List<SFZoom_MeetingHandlerExtension.InviteeDetailsWrapper>) JSON.deserializeStrict(jsonAttendees, List<SFZoom_MeetingHandlerExtension.InviteeDetailsWrapper>.class);
                if(lstAttendees.isEmpty())
                    returnResult.put(false, Label.Select_Attendee_to_Send_Invite_Error_Message);
                else{
                    SFZoom_MeetingHandlerExtension SFZoomMeetingHandlerInstance = new SFZoom_MeetingHandlerExtension((Id) sfMeetingId, parent, true);
                    SFZoomMeetingHandlerInstance.listOfNotInvitedRecordDetails = lstAttendees;
                    SFZoomMeetingHandlerInstance.SendEmailInviteLightning(isUpdate);
                    returnResult.put(true, Label.Email_Successfully_Sent_Message);
                }
            }
        }catch(Exception ex){
            System.debug('SFZoom_LightningEventHandler - sendInviteEmail - Exception: ' + ex.getMessage());
            returnResult.put(false, ex.getMessage());
        }
        return returnResult;
    }
    
    /******************************************************************************************************************
        Method Name  : SendThankyou Email
        Description  : It sends Thankyou email to attendees.
        Date         : 3 Jan 2019.
        Parameter1   : sfMeetingId - It contains salesforce meeting record id
        Parameter2   : jsonAttendees - It contains details of all the selected member in the json format
        Author       : DataColada Pty Ltd
    *******************************************************************************************************************/
    @AuraEnabled
    public static Map<Boolean, String> sendThankyouEmail(String sfMeetingId, String jsonAttendees){
        Map<Boolean, String> returnResult = new Map<Boolean, String>();
        try{
            if(String.isBlank(sfMeetingId))
                returnResult.put(false, Label.Missing_meeting_detail);
            else{
                List<SFZoom_MeetingHandlerExtension.InviteeDetailsWrapper> lstAttendees = (List<SFZoom_MeetingHandlerExtension.InviteeDetailsWrapper>) JSON.deserializeStrict(jsonAttendees, List<SFZoom_MeetingHandlerExtension.InviteeDetailsWrapper>.class);
                if(lstAttendees.isEmpty())
                    returnResult.put(false, Label.No_Attendees);
                else{
                    SFZoom_MeetingHandlerExtension SFZoomMeetingHandlerInstance = new SFZoom_MeetingHandlerExtension((Id) sfMeetingId, null, true);
                    SFZoomMeetingHandlerInstance.listOfAttendedInvitedRecordDetails = lstAttendees;
                    SFZoomMeetingHandlerInstance.sfMeetingId = sfMeetingId;
                    SFZoomMeetingHandlerInstance.isFromLightning = true;
                    SFZoomMeetingHandlerInstance.sendThankYouEmail();
                    returnResult.put(true, Label.Email_Successfully_Sent_Message);
                }
            }
        }catch(Exception ex){
            System.debug('SFZoom_LightningEventHandler - send Thankyou Email - Exception: ' + ex.getMessage());
            returnResult.put(false, ex.getMessage());
        }
        return returnResult;
    }
    
}