force-app/main/default/objects/Zoom_Configuration_Settings__c/Zoom_Configuration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It contains the zoom account configuration setting and API details</description>
    <label>Zoom Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Allow_Multiple_Devices__c.field-meta.xml
<CustomField>
    <fullName>Allow_Multiple_Devices__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It Allows attendees to join from multiple devices</description>
    <inlineHelpText>It Allows attendees to join from multiple devices</inlineHelpText>
    <label>Allow Multiple Devices</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Enforce_Login__c.field-meta.xml
<CustomField>
    <fullName>Enforce_Login__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It contains the setting whether the attendee should be logged in</description>
    <inlineHelpText>It contains the setting whether the attendee should be logged in</inlineHelpText>
    <label>Enforce Login</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/HD_Video__c.field-meta.xml
<CustomField>
    <fullName>HD_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It tells that make video resolution Defaults to HD video</description>
    <inlineHelpText>It tells that make video resolution Defaults to HD video</inlineHelpText>
    <label>HD Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Host_Video__c.field-meta.xml
<CustomField>
    <fullName>Host_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It tells start the video when the host joins the webinar</description>
    <inlineHelpText>It tells start the video when the host joins the webinar</inlineHelpText>
    <label>Host Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Join_Before_Host__c.field-meta.xml
<CustomField>
    <fullName>Join_Before_Host__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It contains value whether participants can join before the host</description>
    <inlineHelpText>It contains value whether participants can join before the host</inlineHelpText>
    <label>Join Before Host</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Panelist_Video__c.field-meta.xml
<CustomField>
    <fullName>Panelist_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It tells that start the video when panelists join the webinar</description>
    <inlineHelpText>It tells that start the video when panelists join the webinar</inlineHelpText>
    <label>Panelist Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Configuration_Settings__c/fields/Share_Survey_Link__c.field-meta.xml
<CustomField>
    <fullName>Share_Survey_Link__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It enables to send the survey link in the Thank you email notification.</description>
    <inlineHelpText>It enables to send the survey link in the Thank you email notification. The Thank you email notification should be enabled for this feature to work.</inlineHelpText>
    <label>Share Survey Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/Zoom_Meeting__c.object-meta.xml
<CustomObject>
    <description>It contains all the meeting data</description>
    <label>Zoom Meeting</label>
    <nameField>
        <label>Zoom Meeting Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zoom Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zoom_Meeting__c/fields/Agenda__c.field-meta.xml
<CustomField>
    <fullName>Agenda__c</fullName>
    <description>It stores the complete meeting agenda</description>
    <inlineHelpText>It stores the complete meeting agenda</inlineHelpText>
    <label>Agenda</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>It stores meeting duration</description>
    <inlineHelpText>It stores meeting duration</inlineHelpText>
    <label>Duration (In Minutes)</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Enforce_Login__c.field-meta.xml
<CustomField>
    <fullName>Enforce_Login__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Only signed-in users can join this meeting</description>
    <inlineHelpText>Only signed-in users can join this meeting</inlineHelpText>
    <label>Enforce Login</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/HD_Video__c.field-meta.xml
<CustomField>
    <fullName>HD_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It tells that make video resolution Defaults to HD video</description>
    <inlineHelpText>It tells that make video resolution Defaults to HD video</inlineHelpText>
    <label>HD Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Host_Video__c.field-meta.xml
<CustomField>
    <fullName>Host_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It tells start the video when the host joins the webinar</description>
    <inlineHelpText>It tells start the video when the host joins the webinar</inlineHelpText>
    <label>Host Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Join_before_Host__c.field-meta.xml
<CustomField>
    <fullName>Join_before_Host__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It stores whether the invitee can join the meeting before the host</description>
    <inlineHelpText>It stores whether the invitee can join the meeting before the host</inlineHelpText>
    <label>Join before Host</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Meeting_Recording_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Recording_URL__c</fullName>
    <inlineHelpText>This stores the meeting recorded play url</inlineHelpText>
    <label>Meeting Recording URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Panelist_Video__c.field-meta.xml
<CustomField>
    <fullName>Panelist_Video__c</fullName>
    <defaultValue>false</defaultValue>
    <description>It tells that start the video when panelists join the webinar</description>
    <inlineHelpText>It tells that start the video when panelists join the webinar</inlineHelpText>
    <label>Panelist Video</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Share_Survey_Link__c.field-meta.xml
<CustomField>
    <fullName>Share_Survey_Link__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Share Survey Link in the Thank you Email Notification. This Feature needs Thank you Email Notification Enabled.</inlineHelpText>
    <label>Share Survey Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>It contains the Start Date of the meeting</description>
    <inlineHelpText>It contains the Start Date of the meeting</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>It contains the Start Time of the Meeting</description>
    <inlineHelpText>It contains the Start Time of the Meeting</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Thank_you_notification__c.field-meta.xml
<CustomField>
    <fullName>Thank_you_notification__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Attendee will receive thank you email by checking this checkbox</inlineHelpText>
    <label>Thank you notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>(GMT+14:00) Line Is. Time (Pacific/Kiritimati)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:45/+13:45) Chatham Standard / Daylight Time (Pacific/Chatham)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00/+13:00) New Zealand Standard / Daylight Time (Pacific/Auckland)</fullName>
            </value>
            <value>
                <fullName>(GMT+13:00) Phoenix Is. Time (Pacific/Enderbury)</fullName>
            </value>
            <value>
                <fullName>(GMT+13:00) Tonga Time (Pacific/Tongatapu)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Fiji Time (Pacific/Fiji)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Petropavlovsk-Kamchatski Time (Asia/Kamchatka)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:30/+11:00) Lord Howe Standard / Daylight Time (Australia/Lord_Howe)</fullName>
            </value>
            <value>
                <fullName>(GMT+11:00) Norfolk Time (Pacific/Norfolk)</fullName>
            </value>
            <value>
                <fullName>(GMT+11:00) Solomon Is. Time (Pacific/Guadalcanal)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:00/+11:00) Australian Eastern Standard / Daylight Time (New South Wales) (Australia/Sydney)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:30/+9:30) Australian Central Standard / Daylight Time (South Australia) (Australia/Adelaide)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:30) Australian Central Standard Time (Northern Territory) (Australia/Darwin)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Japan Standard Time (Asia/Tokyo)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Korea Standard Time (Asia/Seoul)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Philippines Time (Asia/Manila)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Malaysia Time (Asia/Kuala_Lumpur)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) China Standard Time (Asia/Shanghai)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Singapore Time (Asia/Singapore)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) China Standard Time (Asia/Taipei)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Australian Western Standard Time (Australia/Perth)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Hong Kong Time (Asia/Hong_Kong)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) West Indonesia Time (Asia/Jakarta)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Indochina Time (Asia/Bangkok)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Indochina Time (Asia/Ho_Chi_Minh)</fullName>
            </value>
            <value>
                <fullName>(GMT+06:30) Myanmar Time (Asia/Rangoon)</fullName>
            </value>
            <value>
                <fullName>(GMT+06:00) Bangladesh Time (Asia/Dhaka)</fullName>
            </value>
            <value>
                <fullName>(GMT+05:45) Nepal Time (Asia/Kathmandu)</fullName>
            </value>
            <value>
                <fullName>(GMT+05:30) India Standard Time (Asia/Kolkata)</fullName>
            </value>
            <value>
                <fullName>(GMT+05:30) India Standard Time (Asia/Colombo)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <description>It stores topic of the meeting</description>
    <inlineHelpText>It stores topic of the meeting</inlineHelpText>
    <label>Topic</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Meeting__c/recordTypes/Meeting.recordType-meta.xml
<RecordType>
    <fullName>Meeting</fullName>
    <active>true</active>
    <description>It creates a meeting in the Zoom and contains all the fields related to the meeting</description>
    <label>Meeting</label>
</RecordType>

force-app/main/default/objects/Zoom_Metadata__mdt/Zoom_Metadata__mdt.object-meta.xml
<CustomObject>
    <description>It saves record for setting up the Meeting Details</description>
    <label>Zoom Metadata</label>
    <pluralLabel>Zoom Metadata</pluralLabel>
</CustomObject>

force-app/main/default/objects/Zoom_Metadata__mdt/fields/Child_Relationship_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_Relationship_Name__c</fullName>
    <description>It contains the value of the child relationship which is mentioned while creating the relationship field</description>
    <inlineHelpText>It contains the value of the child relationship which is mentioned while creating the relationship field.</inlineHelpText>
    <label>Child Relationship Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zoom_Metadata__mdt/fields/Lookup_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Field_API_Name__c</fullName>
    <description>It contains the API name of the lookup field which has been created on the Meeting object</description>
    <inlineHelpText>It contains the API name of the lookup field which has been created on the Meeting object</inlineHelpText>
    <label>Lookup Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZoomUtils.cls
/*
    The MIT License
    Copyright © 2020 DataColada Pty Ltd

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
 */

global without sharing class ZoomUtils {
    
    /******************************************************************************************************************
    Method Name  : sendEmail
    Description  : It sends email invite to all the members
    Date         : 24 May 2018
    Parameter1   : listOfInvitees - It holds the list of contacts/leads associated with parent object
    Parameter2   : whoId - It holds the contact/lead Id
    Parameter3   : autoRegisterFlag - value from flow/process builder
    Author       : DataColada Pty Ltd
    *******************************************************************************************************************/
    global static void sendEmail(Id whoId,Boolean autoRegister,Id parentRecordId) {

    try{
        String errorMessage;
        Zoom_Meeting__c zoomMeeting ;
        List<Zoom_Meeting__c> listOfMeeting = new List<Zoom_Meeting__c>();
        
        String parentObjectName = String.valueOf(parentRecordId.getSObjectType());
        List<Zoom_Metadata__mdt> listOfMetaData = SFZoom_MeetingHandlerExtension.getMetadataDetails(parentObjectName);
        String lookUpFieldAPIName = listOfMetaData[0].Lookup_Field_API_Name__c;
        //string lookupApiName = getlookupApiName(parentObjectName,listOfMetaData[0].Child_Relationship_Name__c);        
        String query = 'SELECT Name, Agenda__c, Duration__c,Event_Type__c,Meeting_Recording_URL__c,  ';
       query += 'Enforce_Login__c, Join_before_Host__c, Host_Video__c,Thank_you_notification__c,';
       query += 'Start_Date__c, Start_Time__c, Time_Zone__c, Topic__c,Share_Survey_Link__c, ';
       query += 'RecordTypeId, HD_Video__c, Panelist_Video__c, Allow_Multiple_Devices__c,Share_Recording_URL__c,Survey_Link_URL__c, ';
       query += 'Start_Participant_Video_on_Meeting_Join__c, Meeting_URL__c, Auto_Register__c ';
       query += ' FROM Zoom_Meeting__c WHERE ' + String.escapeSingleQuotes(lookUpFieldAPIName) + ' = \''+String.escapeSingleQuotes(parentRecordId)+'\'  LIMIT 1';
       
       listOfMeeting = Database.query(query);      
        
        if(!listOfMeeting.isEmpty() && listOfMeeting.size()>0){
			zoomMeeting = listOfMeeting[0];
            DateTime startDateTime = DateTime.newInstance(zoomMeeting.Start_Date__c, zoomMeeting.Start_Time__c);
            List<Event> listOfEventsToCreate = new List<Event>();
            String strInviteType;
            if(whoId != null && zoomMeeting!=null){
                //Query on event record to check if there is existing event for same contact/lead and meeting
                List<Event> existingEventList = [SELECT Id from Event WHERE WhoId =: whoId AND Zoom_Meeting__c =:zoomMeeting.Id LIMIT 1];
                strInviteType = String.valueOf(whoId.getSObjectType());  
                Event eventToCreateForInvitee = new Event();
				if(!existingEventList.isEmpty()){  //If we found event record then update the Id
					eventToCreateForInvitee.Id = existingEventList[0].Id;
				}
                eventToCreateForInvitee.StartDateTime = startDateTime;
                eventToCreateForInvitee.EndDateTime = startDateTime.addMinutes(Integer.valueOf(zoomMeeting.Duration__c));
                eventToCreateForInvitee.Subject = zoomMeeting.Topic__c;
                eventToCreateForInvitee.Zoom_Meeting__c = zoomMeeting.Id;              
                eventToCreateForInvitee.WhoId = whoId;
                if(strInviteType == 'Contact'){
                    eventToCreateForInvitee.WhatId = parentRecordId; // getWhatId(parentRecordId,whoId, listOfMetaData[0],lookupApiName);
                }
                eventToCreateForInvitee.Description = zoomMeeting.Meeting_URL__c;
                eventToCreateForInvitee.Zoom_Registration_Status__c = Label.Invitee_Event_Status_Initiated;
                listOfEventsToCreate.add(eventToCreateForInvitee);
            }
            if(!listOfEventsToCreate.isEmpty() && listOfEventsToCreate.size() <= 50){
                upsert listOfEventsToCreate; //changed from insert to upsert
            
               List<SFZoom_MeetingHandlerExtension.InviteeDetailsWrapper> listOfInvitees = SFZoom_MeetingHandlerExtension.FindListOfContactOrLeadFromChildRecords(parentRecordId);

               //Send Email Call
               errorMessage = SendEmailToInvitees(zoomMeeting, whoId, autoRegister, listOfInvitees);
            }else if(!listOfEventsToCreate.isEmpty() && listOfEventsToCreate.size() > 50){
                errorMessage = Label.Maximum_Number_of_Invitee_Selection_To_Send_Email_Msg;
            }
        }
    }catch(Exception exe){
          System.debug('Zoom Utils sendEmail - Exception: ' + exe.getMessage());
    }
}

 /******************************************************************************************************************
    Method Name  : extractChildEntries
    Description  : It sends email invite to all the members
    Date         : 07 May 2020
    Parameter1   : zoomMettingIdentity - It holds the zoomMeeting Salesforce identity.
    Parameter2   : whoId - It holds the contact/lead Id
    Parameter3   : active Metadata record  
    Author       : DataColada Pty Ltd
    *******************************************************************************************************************/
    public static List<SObject> extractChildEntries(Id parentRecordId, Zoom_Metadata__mdt zoomSetting )
    {
        
        List<SObject> lstChildRecords = new List<SObject> ();
        try
        {
            string parentLookupApiName = getlookupApiName(parentRecordId, zoomSetting.Child_Relationship_Name__c);	
           
            if(parentRecordId != null){
                
                    lstChildRecords = Database.query('SELECT Id,' + zoomSetting.Contact_Lookup_Field__c +' FROM '+ zoomSetting.Child_Object_API_Name__c + ' WHERE '
                                                    + parentLookupApiName +'=: parentRecordId' );
                }
                
        }
        catch(Exception exe){
           System.debug('Zoom Utils extractChildEntries - Exception: ' + exe.getMessage());
       }
        
        return lstChildRecords;
    }
    
    /******************************************************************************************************************
    Method Name  : getlookupApiName
    Description  : It sends email invite to all the members
    Date         : 07 May 2020
    Parameter1   : zoomMettingIdentity - It holds the zoomMeeting Salesforce identity.
    Parameter2   : whoId - It holds the contact/lead Id
    Parameter3   : active Metadata record  
    Author       : DataColada Pty Ltd
    *******************************************************************************************************************/
    public static string getlookupApiName(Id parentObjectId,string zoomSettingChildRelationshipName)
    {
        String lookupApiName;
        List<SObject> lstChildRecords = new List<SObject> ();
        try
        {
            if(parentObjectId != null && string.isNotBlank(zoomSettingChildRelationshipName)){
                //String parentObjectName = String.valueOf(parentRecordId.getSObjectType());
                String parentObjectName = String.valueOf(parentObjectId.getSObjectType());
                SObjectType objObjectType = Schema.getGlobalDescribe().get(parentObjectName);
                Schema.DescribeSObjectResult   describeresult = objObjectType.getDescribe();
                List<Schema.ChildRelationship>   lstchildrelationships =describeresult.getChildRelationships();
                for (Schema.ChildRelationship relation : lstchildrelationships ){
                    String relationshipName = relation.getRelationshipName();
                    
                    if(relationshipName != null && relationshipName.contains(zoomSettingChildRelationshipName)){
                        lookupApiName = string.valueof(relation.getField());
                        break;
                    }
                }
                
            }
        }
        catch(Exception exe){
           System.debug('Zoom Utils getlookupApiName - Exception: ' + exe.getMessage());
       }
        return  lookupApiName;
    }
  
   
    /******************************************************************************************************************
    Method Name  : SendEmailToInvitees
    Description  : It sends email invite to all the members
    Date         : 24 May 2018
    Parameter1   : listOfInvitees - It holds the list of contacts/leads associated with parent object
    Parameter2   : whoId - It holds the contact/lead Id
    Parameter3   : autoRegisterFlag - value from flow/process builder
    Author       : DataColada Pty Ltd
    *******************************************************************************************************************/
    private static String SendEmailToInvitees(Zoom_Meeting__c zoomMeeting, Id whoId, Boolean autoRegisterFlag,
                                              List<SFZoom_MeetingHandlerExtension.InviteeDetailsWrapper> listOfInvitees){
        String errorMessage;
        String siteURL;
        String mailBody;
        String emailSenderName;
        Boolean isWebinar;
        String mailSentVerificationMsg;
        List<EmailTemplate> emailTemplateToSendEventNotification;

    try{
        String dateToSend = SFZoom_MeetingManagerUtility.changeDateFormat(zoomMeeting.Start_Date__c);
        String timeToSend = SFZoom_MeetingManagerUtility.changeTimeFormat(zoomMeeting.Start_Time__c);
        String emailContent = Label.Event_Invitation_Email_Line1;
        /*String userName = UserInfo.getUserName();
        User activeUser = [SELECT Email FROM User WHERE Username = : userName LIMIT 1];
        String userEmail = activeUser.Email;*/
        String userEmail = UserInfo.getUserEmail();
        if(zoomMeeting.Event_Type__c == Label.Meeting_Record_Type_Name){
            isWebinar = false;
        }else isWebinar = true;
        
        emailTemplateToSendEventNotification = [SELECT htmlValue FROM EmailTemplate 
                                                WHERE developername = :Label.Event_Invitation_Email_Template_Name LIMIT 1];
           		
        If(!emailTemplateToSendEventNotification.isEmpty()){
            mailBody = emailTemplateToSendEventNotification[0].htmlValue;
        }

        //Fetch the custom setting
        Zoom_Configuration_Settings__c zoomConfigurationDetails = Zoom_Configuration_Settings__c.getValues(Label.Config_Details_Custom_Setting_Name);
            If(zoomConfigurationDetails != null){
                if(String.isNotBlank(zoomConfigurationDetails.Site_URL__c)){
                    siteURL =  zoomConfigurationDetails.Site_URL__c.endsWith('/') ? zoomConfigurationDetails.Site_URL__c
                        : zoomConfigurationDetails.Site_URL__c + '/';
                }
                emailSenderName = zoomConfigurationDetails.Email_Sender_Name__c;
            }
        
        //For Auto Register Flag = False
        for(SFZoom_MeetingHandlerExtension.InviteeDetailsWrapper invitee : listOfInvitees){
          String meetingDetails;
            if(invitee.recordId == whoId){
                mailBody = emailTemplateToSendEventNotification[0].htmlValue;
                
                if(!autoRegisterFlag){
                    meetingDetails = ' Type: '+ Label.Webinar_Record_Type_Name + 
                        ' Topic: '+ zoomMeeting.Topic__c + '<br/> Start Date: '+dateToSend + 
                        '<br/> Start Time: '+timeToSend +'<br/> Duration: '+zoomMeeting.Duration__c + ' Minutes' +
                        '<br/> Agenda: '+(String.isNotBlank(zoomMeeting.Agenda__c) ? zoomMeeting.Agenda__c : '' );
                    
                    if(String.isBlank(mailBody)){
                        mailBody = 'Hello '+ invitee.FirstName + emailContent + meetingDetails;
                    }
                    else{
                        if(String.isNotBlank(mailBody) && mailBody.containsIgnoreCase(Label.Invitee_Name)){
                            mailBody = mailBody.replace(Label.Invitee_Name, invitee.LastName);
                        }
                        if(String.isNotBlank(mailBody) && mailBody.containsIgnoreCase(Label.Meeting_or_Webinar_Details)){
                            mailBody = mailBody.replace(Label.Meeting_or_Webinar_Details, meetingDetails);
                        }    
                    }
               
                    String encryptedId = SFZoom_MeetingManagerUtility.EncryptData(invitee.childRecordId);
                    String encryptedConId = SFZoom_MeetingManagerUtility.EncryptData(invitee.RecordId);
                    String encryptedMeetingId = SFZoom_MeetingManagerUtility.EncryptData(zoomMeeting.Id);
                      
                    meetingDetails = Label.Event_Invitation_Email_Registration_Details+' <a href="'+siteURL+
                                        Label.Event_Invitation_VF_Page_Name+'?id='+encryptedId+
                            '&meetingid='+encryptedMeetingId+'&setupobj='+invitee.setupObjectName;
                        meetingDetails += (invitee.type.equalsIgnoreCase('Contact') ? '&conid=' : '&leadid=')
                                + encryptedConId + '" target="_blank">'+Label.Email_Click_Link_Message+'</a> <br/><br/>';
                                       
                    if(!emailTemplateToSendEventNotification.isEmpty()
                       && String.isNotBlank(emailTemplateToSendEventNotification[0].htmlValue) 
                       && String.isNotBlank(mailBody) && mailBody.containsIgnoreCase(Label.Registration_Details))
                    {
                        mailBody = mailBody.replace(Label.Registration_Details, meetingDetails);
                    }
                    
                    //Send Invitation Email To Registrant
                    mailSentVerificationMsg = SFZoom_MeetingManagerUtility.sendEmail(new List<String>{invitee.email}, null,
                                                                                     mailBody, null, emailSenderName, userEmail, 
                                                                                     Label.Event_Invitation_Subject_Label, invitee.RecordId, 
                                                                                     null);
                }
                
                //For Auto Register Flag = True
                if(autoRegisterFlag){
                    SFZoom_MeetingHandlerExtension.AddMeetingOrWebinarRegistrantForAutoRegistration(invitee.firstName, invitee.lastName, invitee.email, 
                                                                                                    zoomMeeting.Name, invitee.RecordId, null, zoomMeeting.Id, isWebinar);
                }
            }
        }
       }catch(Exception exe){
           System.debug('Zoom Utils sendEmailToInvitees - Exception: ' + exe.getMessage());
       }
     return errorMessage;
    }
}